# Generated by Django 5.1.3 on 2024-11-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
